[env]
TERM = "xterm-256color" 

[colors]
cursor = { text="#000000", cursor = "#fcba03"}

[font]
normal = { family = "UbuntuMono Nerd Font", style = "Regular" }
bold = { family = "UbuntuMono Nerd Font", style = "Bold" }
italic = { family = "UbuntuMono Nerd Font", style = "Italic" }
bold_italic = { family = "UbuntuMono Nerd Font", style = "Bold Italic" }

# normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
# bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
# italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
# bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

size = 17 
offset = { x = 0, y = 7 }
glyph_offset = { x = 0, y = 2 }

[window]
dynamic_padding = true
decorations = "None"
startup_mode = "Maximized"
opacity = 0.95
blur = true

[general]
import = [
  "~/.config/alacritty/everforest.toml"
]
































