# Dark
[colors.primary]
background= '#2d353b'
foreground= '#d3c6aa'

[colors.selection]
text = "#d3c6aa"
background = "#414b51"

[colors.normal]
black=   '#343f44'
red=     '#e67e80'
green=   '#a7c080'
yellow=  '#dbbc7f'
blue=    '#7fbbb3'
magenta= '#d699b6'
cyan=    '#83c092'
white=   '#d3c6aa'

[colors.bright]
black=   '#859289'
red=     '#e67e80'
green=   '#a7c080'
yellow=  '#dbbc7f'
blue=    '#7fbbb3'
magenta= '#d699b6'
cyan=    '#83c092'
white=   '#d3c6aa'

# My black: #5c6e77

# Light

# [colors.primary]
# background = '#fdf6e3'
# foreground = '#5c6a72'

# [colors.normal]
# black   = '#5c6a72'
# red     = '#f85552'
# green   = '#8da101'
# yellow  = '#dfa000'
# blue    = '#3a94c5'
# magenta = '#df69ba'
# cyan    = '#35a77c'
# white   = '#e0dcc7'

# [colors.bright]
# black   = '#5c6a72'
# red     = '#f85552'
# green   = '#8da101'
# yellow  = '#dfa000'
# blue    = '#3a94c5'
# magenta = '#df69ba'
# cyan    = '#35a77c'
# white   = '#e0dcc7'
